//
//
// Copyright 2018 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: echo.proto

package echoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	echo "github.com/opensraph/srpc/examples/proto/echo"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EchoName is the fully-qualified name of the Echo service.
	EchoName = "srpc.examples.echo.Echo"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EchoUnaryEchoProcedure is the fully-qualified name of the Echo's UnaryEcho RPC.
	EchoUnaryEchoProcedure = "/srpc.examples.echo.Echo/UnaryEcho"
	// EchoServerStreamingEchoProcedure is the fully-qualified name of the Echo's ServerStreamingEcho
	// RPC.
	EchoServerStreamingEchoProcedure = "/srpc.examples.echo.Echo/ServerStreamingEcho"
	// EchoClientStreamingEchoProcedure is the fully-qualified name of the Echo's ClientStreamingEcho
	// RPC.
	EchoClientStreamingEchoProcedure = "/srpc.examples.echo.Echo/ClientStreamingEcho"
	// EchoBidirectionalStreamingEchoProcedure is the fully-qualified name of the Echo's
	// BidirectionalStreamingEcho RPC.
	EchoBidirectionalStreamingEchoProcedure = "/srpc.examples.echo.Echo/BidirectionalStreamingEcho"
)

// EchoClient is a client for the srpc.examples.echo.Echo service.
type EchoClient interface {
	// UnaryEcho is unary echo.
	UnaryEcho(context.Context, *connect.Request[echo.EchoRequest]) (*connect.Response[echo.EchoResponse], error)
	// ServerStreamingEcho is server side streaming.
	ServerStreamingEcho(context.Context, *connect.Request[echo.EchoRequest]) (*connect.ServerStreamForClient[echo.EchoResponse], error)
	// ClientStreamingEcho is client side streaming.
	ClientStreamingEcho(context.Context) *connect.ClientStreamForClient[echo.EchoRequest, echo.EchoResponse]
	// BidirectionalStreamingEcho is bidi streaming.
	BidirectionalStreamingEcho(context.Context) *connect.BidiStreamForClient[echo.EchoRequest, echo.EchoResponse]
}

// NewEchoClient constructs a client for the srpc.examples.echo.Echo service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEchoClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EchoClient {
	baseURL = strings.TrimRight(baseURL, "/")
	echoMethods := echo.File_echo_proto.Services().ByName("Echo").Methods()
	return &echoClient{
		unaryEcho: connect.NewClient[echo.EchoRequest, echo.EchoResponse](
			httpClient,
			baseURL+EchoUnaryEchoProcedure,
			connect.WithSchema(echoMethods.ByName("UnaryEcho")),
			connect.WithClientOptions(opts...),
		),
		serverStreamingEcho: connect.NewClient[echo.EchoRequest, echo.EchoResponse](
			httpClient,
			baseURL+EchoServerStreamingEchoProcedure,
			connect.WithSchema(echoMethods.ByName("ServerStreamingEcho")),
			connect.WithClientOptions(opts...),
		),
		clientStreamingEcho: connect.NewClient[echo.EchoRequest, echo.EchoResponse](
			httpClient,
			baseURL+EchoClientStreamingEchoProcedure,
			connect.WithSchema(echoMethods.ByName("ClientStreamingEcho")),
			connect.WithClientOptions(opts...),
		),
		bidirectionalStreamingEcho: connect.NewClient[echo.EchoRequest, echo.EchoResponse](
			httpClient,
			baseURL+EchoBidirectionalStreamingEchoProcedure,
			connect.WithSchema(echoMethods.ByName("BidirectionalStreamingEcho")),
			connect.WithClientOptions(opts...),
		),
	}
}

// echoClient implements EchoClient.
type echoClient struct {
	unaryEcho                  *connect.Client[echo.EchoRequest, echo.EchoResponse]
	serverStreamingEcho        *connect.Client[echo.EchoRequest, echo.EchoResponse]
	clientStreamingEcho        *connect.Client[echo.EchoRequest, echo.EchoResponse]
	bidirectionalStreamingEcho *connect.Client[echo.EchoRequest, echo.EchoResponse]
}

// UnaryEcho calls srpc.examples.echo.Echo.UnaryEcho.
func (c *echoClient) UnaryEcho(ctx context.Context, req *connect.Request[echo.EchoRequest]) (*connect.Response[echo.EchoResponse], error) {
	return c.unaryEcho.CallUnary(ctx, req)
}

// ServerStreamingEcho calls srpc.examples.echo.Echo.ServerStreamingEcho.
func (c *echoClient) ServerStreamingEcho(ctx context.Context, req *connect.Request[echo.EchoRequest]) (*connect.ServerStreamForClient[echo.EchoResponse], error) {
	return c.serverStreamingEcho.CallServerStream(ctx, req)
}

// ClientStreamingEcho calls srpc.examples.echo.Echo.ClientStreamingEcho.
func (c *echoClient) ClientStreamingEcho(ctx context.Context) *connect.ClientStreamForClient[echo.EchoRequest, echo.EchoResponse] {
	return c.clientStreamingEcho.CallClientStream(ctx)
}

// BidirectionalStreamingEcho calls srpc.examples.echo.Echo.BidirectionalStreamingEcho.
func (c *echoClient) BidirectionalStreamingEcho(ctx context.Context) *connect.BidiStreamForClient[echo.EchoRequest, echo.EchoResponse] {
	return c.bidirectionalStreamingEcho.CallBidiStream(ctx)
}

// EchoHandler is an implementation of the srpc.examples.echo.Echo service.
type EchoHandler interface {
	// UnaryEcho is unary echo.
	UnaryEcho(context.Context, *connect.Request[echo.EchoRequest]) (*connect.Response[echo.EchoResponse], error)
	// ServerStreamingEcho is server side streaming.
	ServerStreamingEcho(context.Context, *connect.Request[echo.EchoRequest], *connect.ServerStream[echo.EchoResponse]) error
	// ClientStreamingEcho is client side streaming.
	ClientStreamingEcho(context.Context, *connect.ClientStream[echo.EchoRequest]) (*connect.Response[echo.EchoResponse], error)
	// BidirectionalStreamingEcho is bidi streaming.
	BidirectionalStreamingEcho(context.Context, *connect.BidiStream[echo.EchoRequest, echo.EchoResponse]) error
}

// NewEchoHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEchoHandler(svc EchoHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	echoMethods := echo.File_echo_proto.Services().ByName("Echo").Methods()
	echoUnaryEchoHandler := connect.NewUnaryHandler(
		EchoUnaryEchoProcedure,
		svc.UnaryEcho,
		connect.WithSchema(echoMethods.ByName("UnaryEcho")),
		connect.WithHandlerOptions(opts...),
	)
	echoServerStreamingEchoHandler := connect.NewServerStreamHandler(
		EchoServerStreamingEchoProcedure,
		svc.ServerStreamingEcho,
		connect.WithSchema(echoMethods.ByName("ServerStreamingEcho")),
		connect.WithHandlerOptions(opts...),
	)
	echoClientStreamingEchoHandler := connect.NewClientStreamHandler(
		EchoClientStreamingEchoProcedure,
		svc.ClientStreamingEcho,
		connect.WithSchema(echoMethods.ByName("ClientStreamingEcho")),
		connect.WithHandlerOptions(opts...),
	)
	echoBidirectionalStreamingEchoHandler := connect.NewBidiStreamHandler(
		EchoBidirectionalStreamingEchoProcedure,
		svc.BidirectionalStreamingEcho,
		connect.WithSchema(echoMethods.ByName("BidirectionalStreamingEcho")),
		connect.WithHandlerOptions(opts...),
	)
	return "/srpc.examples.echo.Echo/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EchoUnaryEchoProcedure:
			echoUnaryEchoHandler.ServeHTTP(w, r)
		case EchoServerStreamingEchoProcedure:
			echoServerStreamingEchoHandler.ServeHTTP(w, r)
		case EchoClientStreamingEchoProcedure:
			echoClientStreamingEchoHandler.ServeHTTP(w, r)
		case EchoBidirectionalStreamingEchoProcedure:
			echoBidirectionalStreamingEchoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEchoHandler returns CodeUnimplemented from all methods.
type UnimplementedEchoHandler struct{}

func (UnimplementedEchoHandler) UnaryEcho(context.Context, *connect.Request[echo.EchoRequest]) (*connect.Response[echo.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("srpc.examples.echo.Echo.UnaryEcho is not implemented"))
}

func (UnimplementedEchoHandler) ServerStreamingEcho(context.Context, *connect.Request[echo.EchoRequest], *connect.ServerStream[echo.EchoResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("srpc.examples.echo.Echo.ServerStreamingEcho is not implemented"))
}

func (UnimplementedEchoHandler) ClientStreamingEcho(context.Context, *connect.ClientStream[echo.EchoRequest]) (*connect.Response[echo.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("srpc.examples.echo.Echo.ClientStreamingEcho is not implemented"))
}

func (UnimplementedEchoHandler) BidirectionalStreamingEcho(context.Context, *connect.BidiStream[echo.EchoRequest, echo.EchoResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("srpc.examples.echo.Echo.BidirectionalStreamingEcho is not implemented"))
}
