// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file srpc/echo/v1/echo.proto (package srpc.echo.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file srpc/echo/v1/echo.proto.
 */
export const file_srpc_echo_v1_echo: GenFile = /*@__PURE__*/
  fileDesc("ChdzcnBjL2VjaG8vdjEvZWNoby5wcm90bxIMc3JwYy5lY2hvLnYxIh4KC0VjaG9SZXF1ZXN0Eg8KB21lc3NhZ2UYASABKAkiHwoMRWNob1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAky0gIKC0VjaG9TZXJ2aWNlEkQKCVVuYXJ5RWNobxIZLnNycGMuZWNoby52MS5FY2hvUmVxdWVzdBoaLnNycGMuZWNoby52MS5FY2hvUmVzcG9uc2UiABJQChNTZXJ2ZXJTdHJlYW1pbmdFY2hvEhkuc3JwYy5lY2hvLnYxLkVjaG9SZXF1ZXN0Ghouc3JwYy5lY2hvLnYxLkVjaG9SZXNwb25zZSIAMAESUAoTQ2xpZW50U3RyZWFtaW5nRWNobxIZLnNycGMuZWNoby52MS5FY2hvUmVxdWVzdBoaLnNycGMuZWNoby52MS5FY2hvUmVzcG9uc2UiACgBElkKGkJpZGlyZWN0aW9uYWxTdHJlYW1pbmdFY2hvEhkuc3JwYy5lY2hvLnYxLkVjaG9SZXF1ZXN0Ghouc3JwYy5lY2hvLnYxLkVjaG9SZXNwb25zZSIAKAEwAUKzAQoQY29tLnNycGMuZWNoby52MUIJRWNob1Byb3RvUAFaQGdpdGh1Yi5jb20vb3BlbnNyYXBoL3NycGMvZXhhbXBsZXMvX3Byb3RvL2dvL3NycGMvZWNoby92MTtlY2hvdjGiAgNTRViqAgxTcnBjLkVjaG8uVjHKAg1TcnBjXEVjaG9fXFYx4gIZU3JwY1xFY2hvX1xWMVxHUEJNZXRhZGF0YeoCDlNycGM6OkVjaG86OlYxYgZwcm90bzM");

/**
 * EchoRequest is the request for echo.
 *
 * @generated from message srpc.echo.v1.EchoRequest
 */
export type EchoRequest = Message<"srpc.echo.v1.EchoRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message srpc.echo.v1.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export const EchoRequestSchema: GenMessage<EchoRequest> = /*@__PURE__*/
  messageDesc(file_srpc_echo_v1_echo, 0);

/**
 * EchoResponse is the response for echo.
 *
 * @generated from message srpc.echo.v1.EchoResponse
 */
export type EchoResponse = Message<"srpc.echo.v1.EchoResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message srpc.echo.v1.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export const EchoResponseSchema: GenMessage<EchoResponse> = /*@__PURE__*/
  messageDesc(file_srpc_echo_v1_echo, 1);

/**
 * Echo is the echo service.
 *
 * @generated from service srpc.echo.v1.EchoService
 */
export const EchoService: GenService<{
  /**
   * UnaryEcho is unary echo.
   *
   * @generated from rpc srpc.echo.v1.EchoService.UnaryEcho
   */
  unaryEcho: {
    methodKind: "unary";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * ServerStreamingEcho is server side streaming.
   *
   * @generated from rpc srpc.echo.v1.EchoService.ServerStreamingEcho
   */
  serverStreamingEcho: {
    methodKind: "server_streaming";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * ClientStreamingEcho is client side streaming.
   *
   * @generated from rpc srpc.echo.v1.EchoService.ClientStreamingEcho
   */
  clientStreamingEcho: {
    methodKind: "client_streaming";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * BidirectionalStreamingEcho is bidi streaming.
   *
   * @generated from rpc srpc.echo.v1.EchoService.BidirectionalStreamingEcho
   */
  bidirectionalStreamingEcho: {
    methodKind: "bidi_streaming";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_srpc_echo_v1_echo, 0);

